/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mHnmqurSGVf
 */
import Link from "next/link"
import { Toggle } from "@/components/ui/toggle"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export function HomePage() {
  return (
    <div className="min-h-screen max-w-5xl mx-auto">
      <header className="flex justify-between items-center bg-gray-300 rounded-xl p-4">
        <div className="font-bold text-xl">Dhruv Chouhan</div>
        <nav className="space-x-4">
          <Link className="hover:underline" href="#">
            About
          </Link>
          <Link className="hover:underline" href="#">
            Projects
          </Link>
          <Link className="hover:underline" href="#">
            Skills
          </Link>
          <Link className="hover:underline" href="#">
            Contact
          </Link>
        </nav>
        <div className="flex items-center space-x-2">
          <span className="text-sm">Dark Mode</span>
          <Toggle aria-label="Toggle Dark Mode" className="h-6 w-6" />
        </div>
      </header>
      <main className="space-y-16 p-4">
        <section className="flex flex-col items-center space-y-4" id="hero">
          <Image
            alt="Your Photo"
            className="rounded-full my-6"
            height={400}
            src="/assets/me.jpeg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
            }}
            width={300}
          />
          <h1 className="text-3xl font-bold">Hello, I&rsquo;m a Software Engineer</h1>
        </section>
        <section className="space-y-4" id="about">
          <h2 className="text-2xl font-bold">About Me</h2>
          <p className="max-w-prose">I&rsquo;m a passionate software developer. I love to explore different technologies and trends. I like problem solving and contributing to open source projects.</p>
          <h3 className="text-xl font-bold">Education & Certifications</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Your education background</li>
            <li>Your relevant certifications</li>
          </ul>
          <h3 className="text-xl font-bold">Skills</h3>
          <div className="flex flex-wrap gap-2">
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 1</span>
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 2</span>
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 3</span>
          </div>
        </section>
        <section className="space-y-4" id="projects">
          <h2 className="text-2xl font-bold">Projects</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Project 1</CardTitle>
              </CardHeader>
              <CardContent>
                <Image
                  alt="Project 1"
                  className="object-cover w-full h-60"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <p className="mt-4">Project 1 description</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Project 2</CardTitle>
              </CardHeader>
              <CardContent>
                <Image
                  alt="Project 2"
                  className="object-cover w-full h-60"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <p className="mt-4">Project 2 description</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Project 3</CardTitle>
              </CardHeader>
              <CardContent>
                <Image
                  alt="Project 3"
                  className="object-cover w-full h-60"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <p className="mt-4">Project 3 description</p>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="space-y-4" id="skills">
          <h2 className="text-2xl font-bold">Skills</h2>
          <div className="flex flex-wrap gap-2">
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 1</span>
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 2</span>
            <span className="px-2 py-1 rounded bg-gray-200">Your skill 3</span>
          </div>
        </section>
        <section className="space-y-4" id="contact">
          <h2 className="text-2xl font-bold">Contact</h2>
          <p className="max-w-prose">Your contact information, including email and social media links.</p>
          <Button className="w-full sm:w-auto" variant="outline">
            Download Resume
          </Button>
        </section>
      </main>
      <footer className="flex items-center justify-center py-4 border-t">
        <p className="text-sm text-gray-500">© 2024 Your Name</p>
      </footer>
    </div>
  )
}
